version: "3"
services:
    youdl:
        image: youdl
        build: 
            context: ./
            dockerfile: Dockerfile
        container_name: youdl
        restart: "unless-stopped"
        ports: 
            - 5000:5000
        volumes: 
            - ./videos:/videos
            - ./ydl.conf:/app/ydl.conf
            # - ./app:/app
